spring:
  profiles:
    active: development
  output:
    ansi:
      enabled: ALWAYS
---
enuo:
  version: 1.0.0
  account:
    ticket: ticket
  msg: development
server:
  port: 8090
spring:
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  profiles: development
  application:
    name: enuocms-boot
  redis:
      host: 127.0.0.1
      port: 6379
  datasource:
      account:
          jdbc-url: jdbc:mysql://127.0.0.1:3306/enuocms_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
      business:
          jdbc-url: jdbc:mysql://127.0.0.1:3306/enuocms_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/enuocms_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  freemarker:
    template-loader-path: classpath:/templates
    auto_import: /shared/common.ftl as p
  mvc:
    static-path-pattern: /static/**
#mybatis:
#  type-aliases-package: com.enuocms.account.*.mapper
#  type-handlers-package: com.enuocms.core.mapper
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.enuocms.*.model
mapper:
  mappers: com.enuocms.core.mapper.EnuoMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
log4j:
  rootLogger: WARN
logging:
  file: /tmp/enuocms-boot-debug.log
---
enuo:
  version: 1.0.0
  account:
    ticket: ticket
  msg: production
server:
  port: 8090
spring:
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  profiles: production
  application:
    name: enuocms-boot
  redis:
    host: 127.0.0.1
    port: 6379
    password:
log4j:
  rootLogger: WARN