
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by zhanxp@me.com
//
//     If any question, please let's know.
//     It's a great help for improve our templates
// </auto-generated>
//------------------------------------------------------------------------------

using Com.EnuoCms.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Com.EnuoCms.Service
{
    public class AdminDeleteCommandHandler : ICommandHandler<AdminDeleteCommand>
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IAdminRepository AdminRepository;
        public AdminDeleteCommandHandler(IAdminRepository AdminRepository, IUnitOfWork unitOfWork)
        {
            this.AdminRepository = AdminRepository;
            this.unitOfWork = unitOfWork;
        }

        public ICommandResult Execute(AdminDeleteCommand command)
        {
            try
            {
                foreach (var item in command.itemId)
                {
                    var voidReason = AdminRepository.GetById(item);
                    AdminRepository.Delete(voidReason);
                }
              
                unitOfWork.Commit();

                return new CommandResult(true);
            }
            catch (Exception ex)
            {
                return new CommandResult(false,ex.Message);
            }
        }
    }
}
