
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by zhanxp@me.com
//
//     If any question, please let's know.
//     It's a great help for improve our templates
// </auto-generated>
//------------------------------------------------------------------------------


using Com.EnuoCms.IService;
using Com.EnuoCms.Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Com.EnuoCms.Service
{
    public class AdminCreateOrUpdateCommandHandler : ICommandHandler<AdminCreateOrUpdateCommand>
    {
        private readonly IUnitOfWork unitOfWork;

        private readonly IAdminRepository AdminRepository;
        public AdminCreateOrUpdateCommandHandler(IAdminRepository AdminRepository, IUnitOfWork unitOfWork)
        {
            this.AdminRepository = AdminRepository;
            this.unitOfWork = unitOfWork;
        }

        public ICommandResult Execute(AdminCreateOrUpdateCommand command)
        {
            Admin ent = command.ent;
            if (ent.ID <= 0)
                AdminRepository.Add(ent);
            else
                AdminRepository.Update(ent);

            unitOfWork.Commit();
            return new CommandResult(true);
        }
    }
}
