
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by zhanxp@me.com
//
//     If any question, please let's know.
//     It's a great help for improve our templates
// </auto-generated>
//------------------------------------------------------------------------------


using Com.EnuoCms.IService;
using Com.EnuoCms.Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Com.EnuoCms.Service
{
    public class CategoryCreateOrUpdateCommandHandler : ICommandHandler<CategoryCreateOrUpdateCommand>
    {
        private readonly IUnitOfWork unitOfWork;

        private readonly ICategoryRepository CategoryRepository;
        public CategoryCreateOrUpdateCommandHandler(ICategoryRepository CategoryRepository, IUnitOfWork unitOfWork)
        {
            this.CategoryRepository = CategoryRepository;
            this.unitOfWork = unitOfWork;
        }

        public ICommandResult Execute(CategoryCreateOrUpdateCommand command)
        {
            Category ent = command.ent;
            if (ent.ID <= 0)
                CategoryRepository.Add(ent);
            else
                CategoryRepository.Update(ent);

            unitOfWork.Commit();
            return new CommandResult(true);
        }
    }
}
