// <auto-generated />
using System;
using Enuo.Dotnet.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Enuo.Dotnet.Web.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20210617085217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Enuo.Dotnet.Model.Article", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("content")
                        .HasColumnType("text");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("creater")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("creater");

                    b.Property<int>("entStatus")
                        .HasColumnType("int")
                        .HasColumnName("ent_status");

                    b.Property<int>("entTypes")
                        .HasColumnType("int")
                        .HasColumnName("ent_types");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("update_date");

                    b.Property<string>("updater")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updater");

                    b.HasKey("id");

                    b.ToTable("article");
                });
#pragma warning restore 612, 618
        }
    }
}
