workspace 'enuocms'
project 'ios.xproject'

platform :ios,'8.0'

def pods
    pod 'AFNetworking', '~>2.5.4'
    pod 'JSONKit-NoWarning', '~> 1.2'
    pod 'MMDrawerController', '~> 0.6.0'
    pod 'MBProgressHUD'
    pod 'Toast', '~> 2.4'
    pod 'FMDB', '~> 2.5'
    pod 'LKDBHelper', '~> 2.1.8'
    pod 'MJRefresh', '~> 2.4.12'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'Base64', '~> 1.0.1'
    pod 'OpenUDID', '~> 1.0.0'
end

target 'ios' do
  pods
end