
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by zhanxp@me.com
//
//     If any question, please let's know.
//     It's a great help for improve our templates
// </auto-generated>
//------------------------------------------------------------------------------


using Com.EnuoCms.IService;
using Com.EnuoCms.Model.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Com.EnuoCms.Service
{
    public class ArticleCreateOrUpdateCommandHandler : ICommandHandler<ArticleCreateOrUpdateCommand>
    {
        private readonly IUnitOfWork unitOfWork;

        private readonly IArticleRepository ArticleRepository;
        public ArticleCreateOrUpdateCommandHandler(IArticleRepository ArticleRepository, IUnitOfWork unitOfWork)
        {
            this.ArticleRepository = ArticleRepository;
            this.unitOfWork = unitOfWork;
        }

        public ICommandResult Execute(ArticleCreateOrUpdateCommand command)
        {
            Article ent = command.ent;
            if (ent.ID <= 0)
                ArticleRepository.Add(ent);
            else
                ArticleRepository.Update(ent);

            unitOfWork.Commit();
            return new CommandResult(true);
        }
    }
}
