
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by zhanxp@me.com
//
//     If any question, please let's know.
//     It's a great help for improve our templates
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using Com.EnuoCms.Model;
using Com.EnuoCms.Model.Entities;

namespace Com.EnuoCms.IService
{
    public class EnuoCmsDataContex : DbContext
    {
        public EnuoCmsDataContex() : base("EnuoCmsDataContex") { }
       

        public EnuoCmsDataContex(bool isLazy)
        {
            this.Configuration.ProxyCreationEnabled = isLazy;
            this.Configuration.LazyLoadingEnabled = isLazy;
        }

        public virtual void Commit()
        {
            base.SaveChanges();
        }

        public DbSet<Admin> AdminSet { get; set; }
        public DbSet<Article> ArticleSet { get; set; }
        public DbSet<Category> CategorySet { get; set; }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
       
    }
}
