# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('ent_types', models.IntegerField()),
                ('ent_status', models.IntegerField()),
                ('creater', models.IntegerField()),
                ('updater', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
